language: ruby
cache: bundler
dist: trusty
rvm:
- 2.3.1
services:
  - postgresql
addons:
  postgresql: "9.6"
install:
  - bundle install --jobs=3 --retry=3 --without production development
script:
  - bundle exec rake db:setup
  - bundle exec rake spec
